name: run-job-if-previous-fails

on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: exit 1

      - run: echo -e "yeah!"
        if: ${{ success() || failure() }}

  job-2:
    runs-on: ubuntu-latest
    # if: ${{ success() || failure() }}
    needs:
      - job-1
    steps:
      - uses: actions/checkout@v3

      - run: echo -e "yeah!"
